### ISSUE TITLE
error not a git repository

### ISSUE THREAD

**Issue by Linux4ever** [de-poltorasky/redmine_git_sync#2]
I am getting the following error when adding your plugin via a mount on to this docker image "redmine:5.1.4-bookworm"

fatal: not a git repository (or any parent up to mount point /usr/src/redmine)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

/usr/src/redmine/plugins/redmine_git_sync/app/controllers/git_sync_controller.rb:4:in `<class:GitSyncController>': undefined method `id' for nil:NilClass (NoMethodError)
project_base_dir = File.join(Rails.root, 'files', 'git_repositories', "*_#{@project.id}")
from /usr/src/redmine/plugins/redmine_git_sync/app/controllers/git_sync_controller.rb:1:in `<top (required)>'

I tried your git clone method to clone your plugin into plugins folder or download from github and place the files there into plugins folder.

**Comment by de-poltorasky** [comment]
Hi,
should be ok now. I had an issue on my last code update.
Regards
